apiVersion: v2
name: prometheus-community
description: A Helm chart for Kubernetes
version: 0.1.0
dependencies:
- name: prometheus-community
  version: 6.26.8
  repository: https://prometheus-community.github.io/helm-charts
  alias: prometheus